import React, { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import Svg, { Circle } from 'react-native-svg';
import { api } from '../services/api';
import { useAuth } from '../services/AuthContext';
import { COLORS, WASTE_META } from '../utils/constants';
import { ScreenHeader, StatusPill } from './shared';
export default function AnalyticsScreen({ navigation }: any){ const {token}=useAuth(); const [s,setS]=useState<any>(); useEffect(()=>{api.getAnalytics(token??'').then(r=>setS(r.statistics))},[token]); const dist=s?.distribution??{}; const weekly=s?.weekly??[]; return <ScrollView style={styles.container} contentContainerStyle={{paddingBottom:30}}><ScreenHeader title="Waste Analytics" back navigation={navigation}/><View style={styles.grid}>{[['1,247','Total Classified'],['73%','Recycling Rate'],['342','This Month'],['89','This Week']].map(c=><View style={styles.card} key={c[1]}><Text style={styles.value}>{c[0]}</Text><Text style={styles.label}>{c[1]}</Text></View>)}</View><View style={styles.panel}><Text style={styles.panelTitle}>Waste Distribution</Text><View style={styles.chartRow}><Svg width={160} height={160} viewBox="0 0 160 160"><Circle cx="80" cy="80" r="52" stroke={COLORS.blue} strokeWidth="34" fill="none"/><Circle cx="80" cy="80" r="52" stroke={COLORS.brightGreen} strokeWidth="34" fill="none" strokeDasharray="90 327" rotation="-90" origin="80,80"/><Circle cx="80" cy="80" r="52" stroke={COLORS.yellow} strokeWidth="34" fill="none" strokeDasharray="55 327" strokeDashoffset="-90" rotation="-90" origin="80,80"/></Svg><View>{Object.keys(dist).map(k=><Text key={k} style={styles.legend}><Text style={{color:WASTE_META[k].color}}>■ </Text>{k}{'\n'}{dist[k]}%</Text>)}</View></View></View><View style={styles.panel}><Text style={styles.panelTitle}>Weekly Trend</Text><View style={styles.bars}>{weekly.map((v:number,i:number)=><View key={i} style={[styles.bar,{height:v,backgroundColor:i===3?COLORS.brightGreen:COLORS.green}]}/>)}</View></View><View style={styles.panel}><Text style={styles.panelTitle}>Overflow Risk Predictions</Text>{(s?.risk??[]).map((r:any)=><View key={r.bin} style={styles.risk}><Text style={styles.riskText}>{r.bin}</Text><Text style={styles.riskText}>{r.days_left}</Text><StatusPill status={r.risk}/></View>)}</View></ScrollView>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:COLORS.background},grid:{flexDirection:'row',flexWrap:'wrap',gap:10,padding:16},card:{width:'48%',height:70,borderWidth:1.5,borderColor:COLORS.border,borderRadius:8,padding:12},value:{color:'#fff',fontSize:22,fontWeight:'900'},label:{color:COLORS.textMuted,fontWeight:'800',fontSize:11},panel:{marginHorizontal:16,marginBottom:14,borderWidth:1.5,borderColor:COLORS.border,borderRadius:8,padding:14},panelTitle:{color:'#fff',fontWeight:'900',marginBottom:12},chartRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-around'},legend:{color:'#fff',fontWeight:'800',lineHeight:19},bars:{height:100,flexDirection:'row',alignItems:'flex-end',gap:10,paddingHorizontal:20},bar:{width:24,borderRadius:3},risk:{height:33,borderBottomWidth:1,borderColor:COLORS.border,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},riskText:{color:'#fff',fontWeight:'800',width:95}});
