import React, { useState } from 'react';
import { ActivityIndicator, Alert, Image, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { Ionicons } from '@expo/vector-icons';
import { api } from '../services/api';
import { useAuth } from '../services/AuthContext';
import { COLORS, WASTE_META } from '../utils/constants';
import { ScreenHeader, StatusPill } from './shared';

export default function ClassifyScreen({ navigation }: any) { const { token }=useAuth(); const [uri,setUri]=useState<string>(); const [loading,setLoading]=useState(false); const [prediction,setPrediction]=useState<any>();
  const pick=async(camera=false)=>{ const res=camera?await ImagePicker.launchCameraAsync({quality:.8}):await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,quality:.8}); if(!res.canceled){setUri(res.assets[0].uri);setPrediction(undefined);} };
  const demo=()=>{setUri('demo-plastic-bottle.jpg'); setPrediction(undefined);}; const classify=async()=>{ if(!uri) return; setLoading(true); try{ const r=await api.uploadImage(token??'',uri); setPrediction(r.prediction);}catch{Alert.alert('Unable to classify');} setLoading(false);}; const meta=prediction?WASTE_META[prediction.category]:undefined;
  return <ScrollView style={styles.container}><ScreenHeader title="AI Waste Classifier" back navigation={navigation}/><View style={styles.zone}>{!uri?<><Ionicons name="cloud-upload-outline" size={44} color={COLORS.green}/><Text style={styles.title}>Upload or Capture Image</Text><Text style={styles.sub}>Tap to select from gallery or use camera</Text><TouchableOpacity onPress={demo}><Text style={styles.link}>Tap to demo AI classification →</Text></TouchableOpacity><View style={styles.actions}><TouchableOpacity style={styles.action} onPress={()=>pick(false)}><Text style={styles.actionText}>Gallery</Text></TouchableOpacity><TouchableOpacity style={styles.action} onPress={()=>pick(true)}><Text style={styles.actionText}>Camera</Text></TouchableOpacity></View></>:<><View style={styles.preview}>{uri.startsWith('demo')?<Text style={{fontSize:54}}>🥤</Text>:<Image source={{uri}} style={StyleSheet.absoluteFillObject}/>}</View><TouchableOpacity style={styles.btn} onPress={classify}>{loading?<ActivityIndicator color="#fff"/>:<Text style={styles.btnText}>Classify Waste</Text>}</TouchableOpacity></>}{prediction&&meta&&<View style={styles.result}><Text style={styles.resultTitle}>{meta.icon ? '✅' : ''} {prediction.category} Waste</Text><StatusPill status={`${prediction.confidence}% confidence`}/><Text style={styles.resultText}>Recommended: {prediction.recommended_bin}</Text><Text style={styles.resultText}>{prediction.recycling_tip}</Text><Text style={styles.resultText}>{prediction.environmental_impact}</Text></View>}</View></ScrollView> }
const styles=StyleSheet.create({container:{flex:1,backgroundColor:COLORS.background},zone:{margin:14,borderWidth:1.5,borderStyle:'dashed',borderColor:COLORS.border,borderRadius:10,minHeight:152,alignItems:'center',justifyContent:'center',padding:16},title:{color:'#fff',fontWeight:'900',marginTop:8},sub:{color:COLORS.textMuted,fontSize:12,fontWeight:'700',marginTop:5},link:{color:COLORS.green,fontSize:12,fontWeight:'800',marginTop:8},actions:{flexDirection:'row',gap:10,marginTop:14},action:{borderWidth:1,borderColor:COLORS.border,borderRadius:8,paddingHorizontal:18,paddingVertical:8},actionText:{color:'#fff',fontWeight:'800'},preview:{width:'100%',height:150,borderRadius:10,backgroundColor:'#1f211e',alignItems:'center',justifyContent:'center',overflow:'hidden'},btn:{height:42,borderRadius:8,backgroundColor:COLORS.green,alignItems:'center',justifyContent:'center',alignSelf:'stretch',marginTop:14},btnText:{color:'#fff',fontWeight:'900'},result:{alignSelf:'stretch',marginTop:14,padding:14,borderWidth:1,borderColor:COLORS.border,borderRadius:10,backgroundColor:COLORS.card,gap:8},resultTitle:{color:'#fff',fontSize:18,fontWeight:'900'},resultText:{color:COLORS.textMuted,fontWeight:'700',lineHeight:19}});
