import React, { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { api } from '../services/api';
import { useAuth } from '../services/AuthContext';
import { COLORS, WASTE_META } from '../utils/constants';
import { Progress } from './shared';

export default function HomeScreen({ navigation }: any) {
  const { user, token } = useAuth(); const [bins,setBins]=useState<any[]>([]); const [stats,setStats]=useState<any>({});
  useEffect(()=>{ api.getAllBins(token ?? '').then(r=>setBins(r.bins)); api.getAnalytics(token ?? '').then(r=>setStats(r.statistics)); },[token]);
  const cards=[['♻️', stats.total_classified ?? 1247, 'Total Classified'], ['📊', `${stats.recycling_rate ?? 73}%`, 'Recycling Rate'], ['🗑️', bins.length || 5, 'Active Bins'], ['⚠️', bins.filter(b=>b.status!=='Normal').length || 2, 'Bins Near Full']];
  return <ScrollView style={styles.container} contentContainerStyle={{ paddingBottom: 90 }}><View style={styles.hero}><Text style={styles.greet}>Good morning 👋</Text><Text style={styles.name}>{user?.name ?? 'Arjun Kumar'}</Text><Text style={styles.role}>Hyderabad Smart City • {user?.role === 'admin' ? 'Admin' : 'Citizen User'}</Text></View><View style={styles.grid}>{cards.map(c=><View style={styles.card} key={c[2]}><Text style={styles.icon}>{c[0]}</Text><Text style={styles.value}>{c[1]}</Text><Text style={styles.label}>{c[2]}</Text></View>)}</View><TouchableOpacity style={styles.outline} onPress={()=>navigation.navigate('Classify')}><Ionicons name="camera-outline" color={COLORS.white}/><Text style={styles.outlineText}>Classify Waste Now</Text></TouchableOpacity><Text style={styles.section}>Bin Status Overview</Text>{bins.map(bin=>{ const meta=WASTE_META[bin.waste_type]; const color=bin.status==='Full'?COLORS.red:bin.status==='Warning'?COLORS.orange:meta.color; return <TouchableOpacity key={bin.id} style={styles.binRow} onPress={()=>navigation.navigate('SmartBins')}><View style={[styles.dot,{backgroundColor:meta.color}]}/><Text style={styles.binName}>{bin.bin_name} ({bin.waste_type})</Text><Progress percent={bin.fill_percent} color={color}/><Text style={styles.pct}>{bin.fill_percent}%</Text></TouchableOpacity>})}</ScrollView>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:COLORS.background},hero:{height:175,backgroundColor:COLORS.darkGreen,justifyContent:'flex-end',padding:18},greet:{color:COLORS.textMuted,fontSize:12,fontWeight:'800'},name:{color:'#fff',fontSize:18,fontWeight:'900',marginTop:4},role:{color:'#fff',fontSize:12,fontWeight:'800'},grid:{flexDirection:'row',flexWrap:'wrap',gap:10,paddingHorizontal:14,marginTop:-16},card:{width:'48%',height:92,borderWidth:1.5,borderColor:COLORS.border,borderRadius:8,backgroundColor:COLORS.card,padding:12},icon:{fontSize:19},value:{color:'#fff',fontSize:22,fontWeight:'900',marginTop:8},label:{color:COLORS.textMuted,fontSize:11,fontWeight:'800'},outline:{marginHorizontal:14,marginTop:10,height:32,borderWidth:1.5,borderColor:COLORS.border,borderRadius:7,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center'},outlineText:{color:'#fff',fontWeight:'900'},section:{color:'#fff',fontWeight:'900',margin:14,marginTop:22},binRow:{height:31,borderTopWidth:1,borderColor:'#464943',paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:10},dot:{width:10,height:10,borderRadius:5},binName:{color:'#fff',fontWeight:'800',fontSize:12,width:128},pct:{color:'#fff',fontWeight:'800',fontSize:11,width:34,textAlign:'right'}});
