import React, { useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { COLORS } from '../utils/constants';
import { useAuth } from '../services/AuthContext';

export default function LoginScreen({ navigation }: any) {
  const { login } = useAuth();
  const [email, setEmail] = useState('user@wastewise.ai'); const [password, setPassword] = useState('password123'); const [loading, setLoading] = useState(false);
  const submit = async () => { setLoading(true); const res = await login(email, password); setLoading(false); if (!res.success) Alert.alert('Login failed', res.message ?? 'Try demo credentials.'); };
  return <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.container}><View style={styles.top}/><View style={styles.logo}><Text style={styles.logoText}>♻️</Text></View><Text style={styles.name}>WasteWise AI</Text><Text style={styles.sub}>Sign in to continue</Text><Text style={styles.label}>Email Address</Text><TextInput style={styles.input} value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address"/><Text style={styles.label}>Password</Text><TextInput style={styles.input} value={password} onChangeText={setPassword} secureTextEntry/><TouchableOpacity style={styles.btn} onPress={submit}>{loading ? <ActivityIndicator color="#fff"/> : <Text style={styles.btnText}>Login</Text>}</TouchableOpacity><View style={styles.row}><Text style={styles.muted}>Don't have an account? </Text><TouchableOpacity onPress={() => navigation.navigate('Register')}><Text style={styles.link}>Register</Text></TouchableOpacity></View><View style={styles.demo}><Text style={styles.demoText}>Demo credentials:{'\n'}User: user@wastewise.ai | Admin: admin@wastewise.ai</Text></View></ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ container: { flexGrow: 1, backgroundColor: COLORS.background, padding: 22, alignItems: 'stretch' }, top: { height: 84, backgroundColor: COLORS.darkGreen, marginHorizontal: -22, marginTop: -22, marginBottom: 26 }, logo: { alignSelf: 'center', width: 58, height: 58, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.green }, logoText: { fontSize: 32 }, name: { color: COLORS.text, fontSize: 20, fontWeight: '900', textAlign: 'center', marginTop: 12 }, sub: { color: COLORS.textMuted, fontWeight: '700', textAlign: 'center', marginBottom: 20 }, label: { color: COLORS.textMuted, fontSize: 12, fontWeight: '800', marginTop: 12, marginBottom: 7 }, input: { height: 40, borderWidth: 1.5, borderColor: COLORS.border, borderRadius: 6, color: COLORS.text, paddingHorizontal: 12, fontWeight: '700' }, btn: { height: 40, borderWidth: 1.5, borderColor: '#777', borderRadius: 7, alignItems: 'center', justifyContent: 'center', marginTop: 20 }, btnText: { color: COLORS.text, fontWeight: '900' }, row: { flexDirection: 'row', justifyContent: 'center', marginTop: 14 }, muted: { color: COLORS.textMuted, fontWeight: '700', fontSize: 12 }, link: { color: COLORS.green, fontWeight: '900', fontSize: 12 }, demo: { backgroundColor: '#e0f2fe', padding: 13, borderRadius: 7, marginTop: 20 }, demoText: { color: '#0369a1', fontWeight: '800', fontSize: 12 } });
